### ISSUE TITLE
understanding the space and body frame. 

### ISSUE THREAD

**Issue by Joosty** [angadhn/variable-mass-systems-book#2]
**The question below is based on my understanding of the simulation which may be flawed and is outlined below:**

When each simulation was run, two graphs were output representing the same motion of the same body in two different frames. The body frame remains fixed to the body and the space frame is offset by an angle theta to be parallel to H*.

**Question:**

1) What is the purpose of tracking the motion in both frames if they are only separated by an angle? Would it not be enough to plot the motion in one frame?

**Comment by angadhn** [comment]
Plotting the "motion" in one frame would imply solving only for the angular velocity vector and interpreting this vector's motion relative to the body-fixed frame. The "space frame" is, in this case, an inertial frame and is essential to solve for the Euler angles- in the paper, we solve for only one Euler angle. Specifically, it is the second Euler angle of the 3-1-3 (or z-x-z) sequence of rotations.

It would serve you well to pull out a text that discusses the torque-free motion of rigid bodies of constant mass. Here is a terser discussion from MIT OCW: https://ocw.mit.edu/courses/16-61-aerospace-dynamics-spring-2003/c9f02c15c754d5146c30b4dc95e83e33_lecture13.pdf

We can also discuss this further in person.

**Comment by angadhn** [comment]
Also, here is the paper from Wang and Eke that I recommended reading: https://asmedigitalcollection.asme.org/appliedmechanics/article-abstract/62/4/970/396271/Rotational-Dynamics-of-Axisymmetric-Variable-Mass
