### ISSUE TITLE
PLAN: Combining this code with my own extended burn simulations

### ISSUE THREAD

**Issue by Joosty** [angadhn/variable-mass-systems-book#3]
This is more of an idea that I am working on than a question, but I was looking to know if you thought this would be an interesting direction to approach the problem from.

---

**Combining this code with my own extended burn simulations**

Looking over chapters 10 and 11 in Curtis' textbook and this textbook, it seems like I could implement some combination of the extended thrust simulation with the coning motion simulation. If the coning motion simulation plots the nose of the spacecraft and we assume all thrust is parallel with the symmetry axis in the body frame, we could use the angular velocity vector that the simulation generates (ω) to track the angle at which thrust is applied. This would change over the burn, eventually reaching a pure spin by the end, but I feel like it could be interesting to see how it affects the trajectory of a spacecraft since it will initially be unstable.

If I understand it correctly, this section of the code (from the uniform burn code) holds the  angular velocity components with time and I could extract an array to implement in my own code:

![image](https://github.com/user-attachments/assets/3bfcecaa-3d33-4ea1-ab9a-644d7be524bb)

---
I'm not sure if I have gone down a rabbit hole with this, but I just thought I'd put this up here to raise at the next meeting.

**Comment by angadhn** [comment]
Worth pursuing but I would urge that you come to the next meeting with a sketch of what you are hoping to do exactly. You may already have some initial results along this track at this point so your conceptual figure would be useful in that context, as well.
